# Generated by Django 4.0.4 on 2022-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=100000)),
                ('sn', models.CharField(max_length=100000)),
                ('email', models.EmailField(max_length=254)),
                ('time_on_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
