# Generated by Django 4.0.4 on 2022-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_fname_doctor_doc_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
